export function generateData(qtd = 5000) {
    const tiposCorrente = [
        "Bom dia com flores",
        "Fake news política",
        "Receita milagrosa",
        "Corrente religiosa URGENTE",
        "PDF desconhecido",
        "Mensagem motivacional",
        "Horóscopo inventado",
        "Promoção falsa de supermercado",
        "Notícia chocante sem fonte",
        "Dica de saúde duvidosa",
        "Boa noite abençoado",
        "Vídeo aleatório de zap",
        "Filhote fofinho para alegrar o dia",
        "Aviso importante da NASA (falso)",
        "Corrente para ganhar dinheiro",
        "Corrente da sorte",
        "Corrente do anjo",
        "Corrente do universo",
        "Desafio impossível",
        "Notícia de última hora inventada",
        "Corrente do ‘se não enviar vai ter azar’",
        "Mensagem de aniversário genérica",
        "Frase motivacional do Pablo Marçal",
        "Receita de bolo de caneca",
        "Dieta milagrosa de 3 dias",
        "Corrente de foto de santo",
        "Fake news sobre vacina",
        "Fake news sobre política",
        "Fake news sobre remédios naturais",
        "Vídeo de gatinho",
        "Vídeo de acidente duvidoso",
        "Vídeo sem contexto de briga",
        "Mensagem de reflexão",
        "Aviso importante da Globo (falso)",
        "Corrente bíblica",
        "Frase de autoajuda",
        "Corrente para curar doenças",
        "Promoção falsa da Amazon",
        "Promoção falsa do Mercado Livre",
        "Alerta de golpe (falso)",
        "Alerta de falta de combustível",
        "Corrente de prosperidade",
        "Corrente do ‘boa noite grupo’",
        "Boa tarde iluminada",
        "Mensagens de São Longuinho",
        "Vídeo de festa de família",
        "Piada ruim",
        "Figurinha de bom dia",
        "Figurinha de boa noite",
        "Figurinha de Jesus te ama",
        "Fake news sobre o INSS",
        "Fake news sobre aposentadoria",
        "Fake news sobre o FGTS",
        "Receita de chá milagroso",
        "Receita de remédio caseiro",
        "Mensagem de corrente japonesa",
        "Mensagem de corrente indiana",
        "Mensagem de corrente mexicana",
        "Mensagem para ‘limpar a energia’",
        "Mensagem sobre Mercúrio retrógrado",
        "Frase atribuída a Einstein (falsa)",
        "Frase atribuída a Chaplin (falsa)",
        "Frase atribuída a Madre Teresa (falsa)",
        "Frase atribuída a Bill Gates (falsa)",
        "Vídeo de pegadinha",
        "Vídeo emocionante",
        "Vídeo de oração",
        "Vídeo engraçado de tiozão",
        "Vídeo motivacional",
        "Corrente ‘não deixe morrer essa música’",
        "Hoax de segurança digital",
        "Alerta falso da polícia federal",
        "Corrente para mudar foto do perfil",
        "Corrente do ‘escreva amém’",
        "Corrente do ‘compartilhe com 10 pessoas’",
        "Fake news sobre carne contaminada",
        "Fake news sobre arroz plástico",
        "Fake news sobre celular explodindo",
        "Corrente de saúde mental",
        "Mensagem de saudade",
        "Mensagem de fé",
        "Mensagem de coragem",
        "Mensagem de gratidão",
        "Vídeo de chuva",
        "Vídeo de acidente na estrada",
        "Vídeo de animal exótico",
        "Vídeo de fenômeno natural",
        "Vídeo de fantasma (falso)",
        "Corrente do apocalipse",
        "Corrente iluminada",
        "Corrente zen",
        "Corrente de prosperidade financeira",
        "Receita vegana aleatória",
        "Remédio com vinagre",
        "Remédio com limão",
        "Remédio com alho",
        "Remédio com cebola",
        "Corrente de aniversário",
        "Corrente de casamento",
        "Corrente de oração noturna",
        "Corrente para dormir melhor",
        "Frase filosófica inventada",
        "Mensagem espírita",
        "Mensagem católica",
        "Mensagem evangélica",
        "Mensagem budista (aleatória)",
        "Mensagem do dia",
        "Mensagem para começar a semana",
        "Mensagem para terminar a semana",
    ];

    const frequencias = [
        "Diário",
        "Semanal",
        "Quinzenal",
        "Mensal",
        "De hora em hora",
    ];

    const tios = [
        "Tio João",
        "Tia Marlene",
        "Tio Roberto",
        "Tia Graça",
        "Tio Zeca",
        "Tia Cida",
        "Tio Geraldo",
        "Tia Nair",
        "Tio Paulo",
        "Tia Sandra",
        "Tio Milton",
        "Tia Neide",
        "Tio Arlindo",
        "Tia Rosa",
        "Tio Sérgio",

        "Tio Ademar",
        "Tia Lourdes",
        "Tio Gilberto",
        "Tia Penha",
        "Tio Afonso",
        "Tia Marli",
        "Tio Edgar",
        "Tia Doralice",
        "Tio Amarildo",
        "Tia Celeste",
        "Tio Sebastião",
        "Tia Lurdinha",
        "Tio Osvaldo",
        "Tia Ivone",
        "Tio Agenor",
        "Tia Clotilde",
        "Tio Jeremias",
        "Tia Beatriz",
        "Tio Laerte",
        "Tia Miriam",
        "Tio Donizete",
        "Tia Isabel",
        "Tio Juvenal",
        "Tia Marisa",
        "Tio Rubens",
        "Tia Denise",
        "Tio Renato",
        "Tia Cleide",
        "Tio Batista",
        "Tia Fátima",

        "Tio Edvaldo",
        "Tia Marinalva",
        "Tio Laurindo",
        "Tia Maristela",
        "Tio Domingos",
        "Tia Geralda",
        "Tio Natal",
        "Tia Joana",
        "Tio Cláudio",
        "Tia Paulina",
        "Tio Everaldo",
        "Tia Eunice",
        "Tio Getúlio",
        "Tia Iraci",
        "Tio Cássio",
        "Tia Elza",
        "Tio Mauro",
        "Tia Leila",
        "Tio Ismael",
        "Tia Carmem",
        "Tio Norberto",
        "Tia Madalena",
        "Tio Hilário",
        "Tia Rute",
        "Tio Josué",
        "Tia Dalva",
        "Tio Hermes",
        "Tia Solange",
        "Tio Aquiles",
        "Tia Roberta",

        "Tio Clésio",
        "Tia Marina",
        "Tio Joel",
        "Tia Andréia",
        "Tio Wilson",
        "Tia Tatiana",
        "Tio Lindomar",
        "Tia Patrícia",
        "Tio Cezar",
        "Tia Bianca",
        "Tio Hugo",
        "Tia Jaqueline",
        "Tio Renato",
        "Tia Vanessa",
        "Tio Samuel",
        "Tia Rafaela",
        "Tio Nivaldo",
        "Tia Heloísa",
        "Tio Vicente",
        "Tia Márcia",
        "Tio Edivaldo",
        "Tia Daniela",
        "Tio Álvaro",
        "Tia Luciana",
        "Tio Alencar",

        "Tio Raimundo",
        "Tia Sônia",
        "Tio Ivan",
        "Tia Hiroko",
        "Tio Bernardo",
        "Tia Ester",
        "Tio Marcelo",
        "Tia Fabiana",
        "Tio Yuri",
        "Tia Jussara",
        "Tio Diogo",
        "Tia Cris",
        "Tio Henrique",
        "Tia Paola",
    ];

    const sobrenomes = [
        "Silva",
        "Souza",
        "Oliveira",
        "Pereira",
        "Carvalho",
        "Nascimento",
        "Barbosa",
        "Macedo",
        "Ribeiro",
        "Gonçalves",
        "Monteiro",
        "Albuquerque",
        "Moraes",
        "Cardoso",
        "Vieira",
        "Lima",
        "Ferreira",
        "Costa",
        "Rocha",
        "Peixoto",
        "Santos",
        "Azevedo",
        "Moura",
        "Andrade",
        "Camargo",
        "Freitas",
        "Pacheco",
        "Assis",
        "Figueiredo",
        "Tavares",
        "Amaral",
        "Fontes",
        "Rezende",
        "Queiroz",
        "Ramos",
        "Batista",
        "Cavalcanti",
        "Magalhães",
        "Pinto",
        "Passos",
        "Correia",
        "Barros",
        "Sales",
        "Prado",
        "Teixeira",
        "Borges",
        "Machado",
        "Martins",
        "Porto",
        "Gomes",
        "Lopes",
        "Moreira",
        "Fonseca",
        "Ramalho",
        "Garcia",
        "Castro",
        "Braga",
        "Nogueira",
        "Duarte",
        "Furtado",
        "Miranda",
        "Coutinho",
        "Guimarães",
        "Mello",
        "Sarmento",
        "Torres",
        "Serrano",
        "Meneses",
        "Amorim",
        "Cintra",
        "Beltrão",
        "Siqueira",
        "Arruda",
        "Goulart",
        "Lacerda",
        "Muniz",
        "Franco",
        "Carmo",
        "Coimbra",
        "Bueno",
        "Berger",
        "Franceschi",
        "Seabra",
        "Ventura",
        "Araújo",
        "Xavier",
        "Travassos",
        "Leal",
        "Neves",
        "Cruz",
        "Vasconcelos",
        "Simões",
        "Valente",
        "Rangel",
        "Malta",
        "Paiva",
        "Bicalho",
        "Tibúrcio",
        "Abranches",
        "Villela",
        "Barcellos",
        "Giraldi",
        "Antunes",
        "Toledo",
        "Aguiar",
        "Brunetti",
    ];

    const dados = Array.from({ length: qtd }, (_, i) => {
        const tipoCorrente =
            tiposCorrente[Math.floor(Math.random() * tiposCorrente.length)];
        const frequencia =
            frequencias[Math.floor(Math.random() * frequencias.length)];

        const nomeTio = `${tios[Math.floor(Math.random() * tios.length)]} ${
            sobrenomes[Math.floor(Math.random() * sobrenomes.length)]
        }`;

        return {
            matricula: 20230000 + i + 1,
            tipoCorrente,
            frequenciaEnvio: frequencia,
            remetente: nomeTio,
        };
    });

    console.log(`Gerado ${qtd} registros de tios do WhatsApp.`);
    console.log(dados);
    return dados;
}
